stages:
  - build
  - documentation
  
CbmRoot_Continuous:
  stage: build
  tags:
    - CbmRoot
  only:
    - master
  only:
    variables:
      - $CI_PROJECT_PATH == "computing/cbmroot"
  cache:
    paths:
      - build/
      - external/DataTree/
      - external/DataTreeQA/
      - external/KFParticle/
      - external/NicaFemto/
      - external/Vc/
      - external/cppzmq/
      - external/flib_dpb/flib_dpb/
      - external/flib_dpb_20/
      - external/ipc/ipc/
      - external/ipc_legacy/ipc/
      - external/jsroot/
      - external/spadic/spadic/
      - input
      - geometry
      - parameters
  script:
    - set -xv
    - mkdir -p build 
    - cd build
    - find . -name "*.root" -delete
    - find . -name "*_ok" -delete
    - find . -name "all_*.par" -delete
    - cd ..
    - echo "export LINUX_FLAVOUR=Debian8.11" >> Dart.cfg
    - echo "export FAIRSOFT_VERSION=jun19p1" >> Dart.cfg
    - echo "export FAIRROOT_VERSION=v18.2.0" >> Dart.cfg
    - echo "export SIMPATH=/cvmfs/fairroot.gsi.de/fairsoft/\${FAIRSOFT_VERSION}" >> Dart.cfg
    - echo "export FAIRROOTPATH=/cvmfs/fairroot.gsi.de/fairroot/\${FAIRROOT_VERSION}_fairsoft-\${FAIRSOFT_VERSION}" >> Dart.cfg 
    - echo "export BUILDDIR=$PWD/build" >> Dart.cfg
    - echo "export SOURCEDIR=$PWD" >> Dart.cfg
    - echo "export NCPU=5" >> Dart.cfg
    - echo "export PATH=\$SIMPATH/bin:$PATH" >> Dart.cfg
    - ls
    - pwd
    - cat Dart.cfg
    - $PWD/Dart.sh Continuous Dart.cfg
    - cd build
    - find . -name "*.root" -delete
    - find . -name "*_ok" -delete
    - find . -name "all_*.par" -delete
    - cd ..

#FormatCheck:
#  stage: build
#  tags:
#    - CbmRoot
#  only:
#    - merge_requests
#  only:
#    variables:
#      - $CI_MERGE_REQUEST_PROJECT_PATH == "computing/cbmroot"
#  script:
#    - set -xv
#    - echo "export FAIRSOFT_VERSION=jun19p1" >> Dart.cfg
#    - echo "export FAIRROOT_VERSION=v18.2.0" >> Dart.cfg
#    - echo "export SIMPATH=/cvmfs/fairroot.gsi.de/fairsoft/\${FAIRSOFT_VERSION}" >> env.sh
#    - echo "export BUILDDIR=$PWD/build" >> env.sh
#    - echo "export SOURCEDIR=$PWD" >> env.sh
#    - echo "export PATH=\$SIMPATH/bin:$PATH" >> env.sh
#    - ls
#    - pwd
#    - cat env.sh
#    - . ./env.sh && ctest -S cmake/scripts/checkformat.cmake -VV

CbmRoot_Merge:
  stage: build
  tags:
    - CbmRoot
#  only:
#    - merge_requests
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_PROJECT_PATH == "computing/cbmroot"
  script:
    - set -xv
    - echo $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    - echo $CI_MERGE_REQUEST_PROJECT_PATH
    - if [ "$CI_MERGE_REQUEST_PROJECT_PATH" != "computing/cbmroot" ]; then
    -   echo "Should not come here"
    -   exit 1
    - fi
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_MERGE_REQUEST_ID
    - echo $CI_MERGE_REQUEST_IID
    - echo "export LINUX_FLAVOUR=Debian8.11" >> Dart.cfg
    - echo "export FAIRSOFT_VERSION=jun19p1" >> Dart.cfg
    - echo "export FAIRROOT_VERSION=v18.2.0" >> Dart.cfg
    - echo "export SIMPATH=/cvmfs/fairroot.gsi.de/fairsoft/\${FAIRSOFT_VERSION}" >> Dart.cfg
    - echo "export FAIRROOTPATH=/cvmfs/fairroot.gsi.de/fairroot/\${FAIRROOT_VERSION}_fairsoft-\${FAIRSOFT_VERSION}" >> Dart.cfg 
    - echo "export BUILDDIR=$PWD/build" >> Dart.cfg
    - echo "export SOURCEDIR=$PWD" >> Dart.cfg
    - echo "export NCPU=5" >> Dart.cfg
    - echo "export PATH=\$SIMPATH/bin:$PATH" >> Dart.cfg
    - ls
    - pwd
    - cat Dart.cfg
    - $PWD/Dart.sh MergeRequest Dart.cfg

pages:
  stage: documentation
  image: alpine
  tags:
    - docker
  script:
    - apk update && apk add doxygen
    - doxygen doxygen/cbmDoxyfile.conf
    - mv html-doc/html public/
  artifacts:
    paths:
      - public
  only:
    - doxygen
