/** @file CbmTrdPads_v18q_mcbm.h
  * @copyright Copyright (C) 2020 GSI Helmholtzzentrum fuer Schwerionenforschung, Darmstadt
  * @license SPDX-License-Identifier: GPL-3.0-only
  * @authors Florian Uhlig [committer] **/

//
//   TRD pad layout for geometry v18q_mcbm
//
// automatically generated by Create_TRD_Geometry_v18q_mcbm_1e.C
// created 20200331
//

#ifndef CBMTRDPADS_H
#define CBMTRDPADS_H

Int_t fst1_sect_count = 3;
// array of pad geometries in the TRD (trd1mod[1-8])
// 8 modules  // 3 sectors  // 4 values
Float_t fst1_pad_type[8][3][4] =

  // module type 1
  // number of pads:  80 x 36 = 2880
  // pad size sector 1:  0.68 cm x  1.50 cm =  1.01 cm2
  // pad size sector 0:  0.68 cm x  1.50 cm =  1.01 cm2
  {{{54.0, 18.00, 54.0 / 80, 1.50}, {54.0, 18.00, 54.0 / 80, 1.50}, {54.0, 18.00, 54.0 / 80, 1.50}},

   // module type 2
   // number of pads:  80 x 24 = 1920
   // pad size sector 1:  0.68 cm x  2.25 cm =  1.52 cm2
   // pad size sector 0:  0.68 cm x  2.25 cm =  1.52 cm2
   {{54.0, 18.00, 54.0 / 80, 2.25}, {54.0, 18.00, 54.0 / 80, 2.25}, {54.0, 18.00, 54.0 / 80, 2.25}},

   // module type 3
   // number of pads:  80 x 12 =  960
   // pad size sector 1:  0.68 cm x  4.50 cm =  3.04 cm2
   // pad size sector 0:  0.68 cm x  4.50 cm =  3.04 cm2
   {{54.0, 18.00, 54.0 / 80, 4.50}, {54.0, 18.00, 54.0 / 80, 4.50}, {54.0, 18.00, 54.0 / 80, 4.50}},

   // module type 4
   // number of pads:  72 x 20 = 1440
   // pad size sector 1:  0.75 cm x  2.79 cm =  2.09 cm2
   // pad size sector 0:  0.75 cm x  2.79 cm =  2.09 cm2
   {{54.0, 5.58, 54.0 / 72, 2.79}, {54.0, 44.64, 54.0 / 72, 2.79}, {54.0, 5.58, 54.0 / 72, 2.79}},

   //---

   // module type 5
   // number of pads: 128 x 24 = 3072
   // pad size sector 1:  0.72 cm x  4.00 cm =  2.88 cm2
   // pad size sector 0:  0.72 cm x  3.75 cm =  2.70 cm2
   {{92.0, 30.00, 92.0 / 128, 3.75}, {92.0, 32.00, 92.0 / 128, 4.00}, {92.0, 30.00, 92.0 / 128, 3.75}},

   // module type 6
   // number of pads: 128 x 16 = 2048
   // pad size sector 1:  0.72 cm x  5.75 cm =  4.13 cm2
   // pad size sector 0:  0.72 cm x  5.75 cm =  4.13 cm2
   {{92.0, 23.00, 92.0 / 128, 5.75}, {92.0, 46.00, 92.0 / 128, 5.75}, {92.0, 23.00, 92.0 / 128, 5.75}},

   // module type 7
   // number of pads: 128 x  8 = 1024
   // pad size sector 1:  0.72 cm x 11.50 cm =  8.27 cm2
   // pad size sector 0:  0.72 cm x 11.50 cm =  8.27 cm2
   {{92.0, 23.00, 92.0 / 128, 11.50}, {92.0, 46.00, 92.0 / 128, 11.50}, {92.0, 23.00, 92.0 / 128, 11.50}},

   // module type 8
   // number of pads: 128 x  6 =  768
   // pad size sector 1:  0.72 cm x 15.50 cm = 11.14 cm2
   // pad size sector 0:  0.72 cm x 15.25 cm = 10.96 cm2
   {{92.0, 30.50, 92.0 / 128, 15.25}, {92.0, 31.00, 92.0 / 128, 15.50}, {92.0, 30.50, 92.0 / 128, 15.25}}};

#endif
