/* Copyright (C) 2022 FIAS Frankfurt Institute for Advanced Studies, Frankfurt / Main
   SPDX-License-Identifier: GPL-3.0-only
   Authors: Felix Weiglhofer [committer]*/
#include "BuildInfo.h"

// GENERATED BY CMAKE.
// DON'T CHANGE BY HAND. MODIFY .in-File INSTEAD.
namespace cbm::algo::BuildInfo {
const std::string GIT_HASH = "b790b2823a3d6f26bb5c940932cff6933eed2248";
const std::string BUILD_TYPE = "FullWarnings";
const bool GPU_DEBUG = 0;
} // namespace cbm::algo::BuildInfo
