# CMake generated Testfile for 
# Source directory: /home/heinemann/gpuunpacker/cbmroot/macro/reco
# Build directory: /home/heinemann/gpuunpacker/cbmroot/build2/macro/reco
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[reco_cleanup]=] "/usr/bin/cmake" "-P" "/home/heinemann/gpuunpacker/cbmroot/cmake/scripts/cleanmacrodir.cmake")
set_tests_properties([=[reco_cleanup]=] PROPERTIES  FIXTURES_SETUP "reco_cleanup" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;46;add_test;/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;0;")
add_test([=[reco_tra_coll_s100h]=] "/home/heinemann/gpuunpacker/cbmroot/build2/macro/run/run_tra_file.sh" "\"/home/heinemann/gpuunpacker/cbmroot/input/urqmd.auau.10gev.centr.root\"" "3" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h_coll\"" "\"sis100_hadron\"" "kGeant3" "1" "kTRUE")
set_tests_properties([=[reco_tra_coll_s100h]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "segmentation violation" FIXTURES_REQUIRED "reco_cleanup" FIXTURES_SETUP "fixt_reco_tra_coll_sis100_hadron" PASS_REGULAR_EXPRESSION "Macro finished successfully" RESOURCE_LOCK "collParDb_sis100_hadron" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;78;add_test;/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;0;")
add_test([=[reco_tra_sign_s100h]=] "/home/heinemann/gpuunpacker/cbmroot/build2/macro/run/run_tra_file.sh" "\"/home/heinemann/gpuunpacker/cbmroot/input/pluto.auau.8gev.omega.mpmm.0001.root\"" "3" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h_sign\"" "\"sis100_hadron\"" "kGeant3" "1" "kTRUE")
set_tests_properties([=[reco_tra_sign_s100h]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "segmentation violation" FIXTURES_REQUIRED "reco_cleanup" FIXTURES_SETUP "fixt_reco_tra_sign_sis100_hadron" PASS_REGULAR_EXPRESSION "Macro finished successfully" RESOURCE_LOCK "signParDb_sis100_hadron" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;94;add_test;/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;0;")
add_test([=[reco_tra_beam_s100h]=] "/home/heinemann/gpuunpacker/cbmroot/build2/macro/run/run_tra_beam.sh" "9" "\"Au\"" "10" "-1" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h_beam\"" "\"sis100_hadron\"" "kGeant3" "1" "kTRUE")
set_tests_properties([=[reco_tra_beam_s100h]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "segmentation violation" FIXTURES_REQUIRED "reco_cleanup" FIXTURES_SETUP "fixt_reco_tra_beam_sis100_hadron" PASS_REGULAR_EXPRESSION "Macro finished successfully" RESOURCE_LOCK "beamParDb_sis100_hadron" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;109;add_test;/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;0;")
add_test([=[reco_digi_s100h]=] "/home/heinemann/gpuunpacker/cbmroot/build2/macro/run/run_digi.sh" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h_coll\"" "-1" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h\" 1.e7" "1.e6" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h_sign\"" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h_beam\"" "1.e9")
set_tests_properties([=[reco_digi_s100h]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "segmentation violation" FIXTURES_REQUIRED "fixt_reco_tra_coll_sis100_hadron;fixt_reco_tra_sign_sis100_hadron;fixt_reco_tra_beam_sis100_hadron" FIXTURES_SETUP "fixt_reco_digi_ts_sis100_hadron" PASS_REGULAR_EXPRESSION "Macro finished successfully" RESOURCE_LOCK "collParDb_sis100_hadron" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;126;add_test;/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;0;")
add_test([=[reco_reco_sim_s100h]=] "/reco_fairroot.sh" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h.raw.root\"" "\"/home/heinemann/gpuunpacker/cbmroot/build2/macro/reco/data/s100h.reco.root\"")
set_tests_properties([=[reco_reco_sim_s100h]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "segmentation violation" FIXTURES_REQUIRED "fixt_reco_digi_ts_sis100_hadron" FIXTURES_SETUP "fixt_reco_digi_sis100_hadron" PASS_REGULAR_EXPRESSION "Macro finished successfully" RESOURCE_LOCK "collParDb_sis100_hadron" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;142;add_test;/home/heinemann/gpuunpacker/cbmroot/macro/reco/CMakeLists.txt;0;")
